name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-alpine-container-build]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.QUAY_REPO }}/ffmpeg
          tags: latest
          containerfiles: |
            ./Dockerfile
      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ vars.QUAY_REPO }}/ffmpeg
          tags: latest
          registry: ${{ vars.QUAY_REGISTRY }}
          username: ${{ vars.QUAY_REGISTRY_USER }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
